# Generated by Django 3.0.14 on 2022-12-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa wydawcy.', max_length=50)),
                ('website', models.URLField(help_text='Witryna wydawcy.')),
                ('email', models.EmailField(help_text='Adres e-mail wydawcy.', max_length=254)),
            ],
        ),
    ]
